/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.government.election.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lynford
 */
public class VoteWiselyForm extends javax.swing.JFrame {
    
     public Connection con;
     public Statement st;
    /**
     * Creates new form VoteWiselyForm
     */
    public VoteWiselyForm() {
        initComponents();
    }

    VoteWiselyForm(String sid) {
         initComponents();
        userId.setText(sid);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/election_system?zeroDateTimeBehavior=convertToNull","root","");
            st = con.createStatement();
          
            
            
        }catch(Exception e){
            
              JOptionPane.showMessageDialog(null,"Database not Connected");
            
        }
        
        button_vote_visibility();
        
    }
    
    
    /**
     * visibility
     */
    private void button_vote_visibility(){
        
        try{
            
           String sid = userId.getText();
           String sql = "SELECT * FROM voted_candidates WHERE Student_id = '"+sid+"' ";
           PreparedStatement ps_stmt = con.prepareStatement(sql);
           ResultSet rs = ps_stmt.executeQuery();
           
           if(rs.next()){
               
               //JOptionPane.showMessageDialog(null, "ID FOund");
              VoteNow.setVisible(false);
              unablle.setVisible(true);
             
               
           } else {
                //JOptionPane.showMessageDialog(null, "ID not FOund");
                VoteNow.setVisible(true);
                 
                  unablle.setVisible(false);
           }
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userId = new javax.swing.JLabel();
        VoteNow = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        unablle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userId.setText("sid");

        VoteNow.setBackground(new java.awt.Color(0, 51, 51));
        VoteNow.setForeground(new java.awt.Color(255, 255, 255));
        VoteNow.setText("Vote Now");
        VoteNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteNowActionPerformed(evt);
            }
        });

        jButton1.setText("See List of voted candidates");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Student ID: ");

        jButton2.setText("logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        unablle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        unablle.setForeground(new java.awt.Color(102, 0, 0));
        unablle.setText("Unable to Vote Again!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userId)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(VoteNow))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(unablle)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userId)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoteNow)
                    .addComponent(jButton1))
                .addGap(26, 26, 26)
                .addComponent(unablle)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoteNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteNowActionPerformed
        // TODO add your handling code here:
        
            String ssid = userId.getText();
        
               new VoteNowForm(ssid).setVisible(true);
               new VoteNowForm().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                new VoteNowForm().setLocationRelativeTo(null);
                this.dispose();
                
                new VoteWiselyForm().setVisible(false);
    }//GEN-LAST:event_VoteNowActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                String ssid = userId.getText();
        
               new SeeVotedListForm(ssid).setVisible(true);
               new SeeVotedListForm().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                new SeeVotedListForm().setLocationRelativeTo(null);
                this.dispose();
                
                new VoteWiselyForm().setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                new myIndexForm().setVisible(true);
               new myIndexForm().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                new myIndexForm().setLocationRelativeTo(null);
                this.dispose();
                
                new VoteWiselyForm().setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoteWiselyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoteWiselyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoteWiselyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoteWiselyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoteWiselyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoteNow;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel unablle;
    private javax.swing.JLabel userId;
    // End of variables declaration//GEN-END:variables
}
